name: simhumanity
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - slim==5.0
  - r-viridis
  - altair
  - vegafusion-python-embed
  - vegafusion
  - pyranges
  - vl-convert-python
  - pip:
    - tskit
    - msprime
    - pyslim>=1.1.0
    - polars
